# Generated by Django 5.1.1 on 2024-09-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicineCompany', to='app.company'),
        ),
    ]
